services:
  mariadb:
    image: mariadb:latest
    container_name: chatbot_mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ecommerce
    ports:
      - "3308:3306"
    volumes:
      - chatbot_db_data:/var/lib/mysql
    networks:
      - chatbot_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: chatbot_phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "3009:80"
    depends_on:
      - mariadb
    networks:
      - chatbot_network

networks:
  chatbot_network:
    driver: bridge

volumes:
  chatbot_db_data:
